// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: hospitals.sql

package repositories

import (
	"context"
	"database/sql"

	"github.com/oklog/ulid/v2"
)

const createHospital = `-- name: CreateHospital :exec
INSERT INTO hospitals (id, name, created_at, updated_at)
VALUES (?, ?, ?, ?)
`

type CreateHospitalParams struct {
	ID        ulid.ULID
	Name      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateHospital(ctx context.Context, arg CreateHospitalParams) error {
	_, err := q.db.ExecContext(ctx, createHospital,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getHospital = `-- name: GetHospital :one
SELECT id, name, created_at, updated_at, deleted_at
FROM hospitals
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetHospital(ctx context.Context, id ulid.ULID) (Hospital, error) {
	row := q.db.QueryRowContext(ctx, getHospital, id)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
