// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repositories

import (
	"database/sql"
	"encoding/json"

	ulid "github.com/oklog/ulid/v2"
)

type Appointment struct {
	ID          ulid.ULID
	HospitalID  sql.NullString
	DoctorID    sql.NullString
	PatientID   sql.NullString
	TimeslotID  sql.NullString
	Description sql.NullString
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type AuditTrail struct {
	ID            ulid.ULID
	ActorID       sql.NullString
	ActorName     sql.NullString
	ActorRole     sql.NullString
	Action        sql.NullString
	EntityType    sql.NullString
	EntityID      sql.NullString
	AppointmentID sql.NullString
	Message       sql.NullString
	Changes       json.RawMessage
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type Diagnosis struct {
	ID            ulid.ULID
	HospitalID    sql.NullString
	DoctorID      sql.NullString
	PatientID     sql.NullString
	AppointmentID sql.NullString
	Diagnosis     sql.NullString
	Details       sql.NullString
	Dismissed     sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type Hospital struct {
	ID        ulid.ULID
	Name      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Note struct {
	ID            ulid.ULID
	HospitalID    sql.NullString
	AppointmentID sql.NullString
	DoctorID      sql.NullString
	PatientID     sql.NullString
	Content       sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type Prescription struct {
	ID             ulid.ULID
	HospitalID     sql.NullString
	DoctorID       sql.NullString
	PatientID      sql.NullString
	AppointmentID  sql.NullString
	ExpirationDate sql.NullTime
	Details        sql.NullString
	Status         sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type Timeslot struct {
	ID         ulid.ULID
	HospitalID sql.NullString
	UserID     sql.NullString
	Date       sql.NullString
	StartTime  sql.NullString
	EndTime    sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}

type User struct {
	ID         ulid.ULID
	HospitalID sql.NullString
	FirstName  sql.NullString
	LastName   sql.NullString
	Email      sql.NullString
	Password   sql.NullString
	Role       sql.NullString
	Accepted   sql.NullBool
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}
