// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package repositories

import (
	"context"
	"database/sql"

	ulid "github.com/oklog/ulid/v2"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, hospital_id, first_name, last_name, email, password, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID         ulid.ULID
	HospitalID sql.NullString
	FirstName  sql.NullString
	LastName   sql.NullString
	Email      sql.NullString
	Password   sql.NullString
	Role       sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.HospitalID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getHospitalUsers = `-- name: GetHospitalUsers :many
SELECT id, hospital_id, first_name, last_name, email, password, role, accepted, created_at, updated_at, deleted_at
FROM users
WHERE hospital_id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetHospitalUsers(ctx context.Context, hospitalID sql.NullString) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getHospitalUsers, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.Accepted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHospitalUsersByRole = `-- name: GetHospitalUsersByRole :many
SELECT id, hospital_id, first_name, last_name, email, password, role, accepted, created_at, updated_at, deleted_at
FROM users
WHERE hospital_id = ?
  AND role = ?
  AND deleted_at IS NULL
`

type GetHospitalUsersByRoleParams struct {
	HospitalID sql.NullString
	Role       sql.NullString
}

func (q *Queries) GetHospitalUsersByRole(ctx context.Context, arg GetHospitalUsersByRoleParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getHospitalUsersByRole, arg.HospitalID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.Accepted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, hospital_id, first_name, last_name, email, password, role, accepted, created_at, updated_at, deleted_at
FROM users
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id ulid.ULID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Accepted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users
SET hospital_id = ?,
    first_name  = ?,
    last_name   = ?,
    email       = ?,
    password    = ?,
    role        = ?,
    updated_at  = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type UpdateUserParams struct {
	HospitalID sql.NullString
	FirstName  sql.NullString
	LastName   sql.NullString
	Email      sql.NullString
	Password   sql.NullString
	Role       sql.NullString
	UpdatedAt  sql.NullTime
	ID         ulid.ULID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.HospitalID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.UpdatedAt,
		arg.ID,
	)
}
